In [200]:
from sklearn.datasets import load_diabetes
import numpy as np 
import pandas as pd
np.set_printoptions(suppress=True)

In [201]:
x,y=load_diabetes(return_X_y=True)


In [202]:
x.shape

(442, 10)

In [203]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [ ]:
class GDregrssor:
    def __init__(self,learning_rate,epoches):
        self.lr=learning_rate
        self.epoches=epoches
        self.coeff=None
    def fit(self,x,y):
        self.coeff=np.ones(x.shape[1])
        self.coeff=np.insert(self.coeff,0,0).reshape(-1,1)
        x=np.insert(x, 0, 1, axis=1)
        y=y.reshape(-1,1)
        for i in range(self.epoches):
            y_pred=np.dot(x,self.coeff)
            self.coeff=self.coeff-(self.lr*(np.dot((y-y_pred).T,x))).T
 
    


In [205]:
model=GDregrssor(learning_rate=0.01,epoches=100)

In [215]:
model.fit(x,y)
print(model.coeff)


[[150.70298596   0.30125655 -11.31624081  24.65998375  14.8501564
  -20.22660099   8.97123106  -1.87128104   6.24014417  31.32241312
    3.30662349]]
[[150.70298596   0.30125655 -11.31624081  24.65998375  14.8501564
  -20.22660099   8.97123106  -1.87128104   6.24014417  31.32241312
    3.30662349]]


In [214]:
from sklearn.linear_model import LinearRegression
model2=LinearRegression()
model2.fit(x,y)
print(model2.coef_)  
from sklearn.metrics import r2_score
y_pred=model2.predict(x)

r2 = r2_score(y, y_pred)
print(r2)

[ -0.47612079 -11.40686692  24.72654886  15.42940413 -37.67995261
  22.67616277   4.80613814   8.42203936  35.73444577   3.21667372]
0.5177484222203499


In [208]:
class StochasticGDregrssor:
    def __init__(self,learning_rate,epoches):
        self.lr=learning_rate
        self.epoches=epoches
        self.coeff=None
    def fit(self,x,y):
        self.coeff=np.ones(x.shape[1])
        self.coeff=np.insert(self.coeff,0,0).reshape(1,-1)
        x=np.insert(x,0,1,axis=1)
        for i in range(self.epoches):
            for j in range(x.shape[0]):
                idx=np.random.randint(0,x.shape[0])
                y_pred=np.dot(self.coeff,x[idx].reshape(-1,1))
                self.coeff=self.coeff-self.lr*(-2*(np.dot((y[idx]-y_pred),(x[idx].reshape(1,-1)))))
        print(self.coeff)

In [209]:
model=StochasticGDregrssor(0.01,1000)

In [210]:
model.fit(x,y)

[[ 150.28024609   -1.4572278  -234.56211285  523.73916061  329.2906985
  -160.78145345  -36.63469746 -180.57060798  108.45929638  506.99598088
    75.21450217]]


In [211]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x = scaler.fit_transform(x)

model = StochasticGDregrssor(0.0001,1000)

In [212]:
model.fit(x,y)

[[151.86821793  -1.84984049 -11.76337823  24.56542451  14.6201476
  -20.66035657   9.20259549  -3.27400773   6.15378596  29.82863999
    3.29840993]]


In [224]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.datasets import load_diabetes
x,y=load_diabetes(return_X_y=True)
np.set_printoptions(suppress=True)

In [225]:
class StochasticGDregrssor:
    def __init__(self,learning_rate,epoches):
        self.lr=learning_rate
        self.epoches=epoches
        self.coeff=None
    def fit(self,x,y):
        self.coeff=np.ones(x.shape[1])
        self.coeff=np.insert(self.coeff,0,0).reshape(1,-1)
        x=np.insert(x,0,1,axis=1)
        for i in range(self.epoches):
            for j in range(x.shape[0]):
                idx=np.random.randint(0,x.shape[0])
                y_pred=np.dot(self.coeff,x[idx].reshape(-1,1))
                self.coeff=self.coeff-self.lr*(-2*(np.dot((y[idx]-y_pred),(x[idx].reshape(1,-1)))))
        print(self.coeff)

In [233]:
class GDregrssor:
    def __init__(self,learning_rate,epoches):
        self.lr=learning_rate
        self.epoches=epoches
        self.coeff=None
    def fit(self,x,y):
        self.coeff=np.ones(x.shape[1])
        self.coeff=np.insert(self.coeff,0,0).reshape(-1,1)
        x=np.insert(x, 0, 1, axis=1)
        y=y.reshape(-1,1)
        for i in range(self.epoches):
            y_pred=np.dot(x,self.coeff)
            gradient=np.dot((y-y_pred).T,x)/x.shape[0]*-2
            self.coeff=self.coeff-(self.lr*gradient).T
        print(self.coeff)

In [234]:
model1=StochasticGDregrssor(0.0001,10000)
model2=GDregrssor(0.0001,10000)
model3=LinearRegression()
model1.fit(x,y)
model2.fit(x,y)
model3.fit(x,y)
print(model3.coef_)

[[ 152.38180933    9.95299545 -184.21459814  475.22826     296.78383397
   -36.78429933  -99.89842191 -204.92786703  130.82773823  396.44525561
   122.45336358]]
[[131.54857394]
 [  2.34814745]
 [  1.29461407]
 [  5.25562104]
 [  4.19665798]
 [  2.51327992]
 [  2.23671459]
 [ -1.86220818]
 [  4.10591838]
 [  5.09841889]
 [  3.76113171]]
[ -10.0098663  -239.81564367  519.84592005  324.3846455  -792.17563855
  476.73902101  101.04326794  177.06323767  751.27369956   67.62669218]


In [237]:
class GDRegressor:

    def __init__(self, learning_rate=0.01, epochs=1000):
        self.lr = learning_rate
        self.epochs = epochs

    def fit(self, x, y):

        x = np.insert(x, 0, 1, axis=1)
        y = y.reshape(-1,1)

        self.coeff = np.zeros((x.shape[1],1))

        for _ in range(self.epochs):

            y_pred = np.dot(x, self.coeff)

            gradient = -(2/x.shape[0]) * np.dot(x.T, (y-y_pred))

            self.coeff -= self.lr * gradient

        return self

In [238]:
model=GDRegressor(learning_rate=0.0001, epochs=10000)
model.fit(x,y)
print(model.coeff)

[[131.54857394]
 [  1.36105612]
 [  0.3035524 ]
 [  4.26934926]
 [  3.211302  ]
 [  1.53176713]
 [  1.25365748]
 [ -2.86914551]
 [  3.12251744]
 [  4.11535812]
 [  2.77689317]]
