In [131]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder,StandardScaler

np.set_printoptions(suppress=True)


In [132]:
df=pd.read_csv("logistic-regression/Social_Network_Ads.csv")
df["Gender"]

0        Male
1        Male
2      Female
3      Female
4        Male
        ...  
395    Female
396      Male
397    Female
398      Male
399    Female
Name: Gender, Length: 400, dtype: str

In [133]:
encoder=OneHotEncoder(sparse_output=False)
encoded=encoder.fit_transform(df[["Gender"]])
df_ecoded=pd.DataFrame(encoded,columns=encoder.get_feature_names_out(),index=df.index)
df=pd.concat([df,df_ecoded],axis=1)
df=df.drop("Gender",axis=1)

In [134]:
scalar=StandardScaler()
scaled_salary=scalar.fit_transform(df[["EstimatedSalary"]])
df["EstimatedSalary"]=scaled_salary

scalar_age=StandardScaler()
scaled_age=scalar_age.fit_transform(df[["Age"]])
df["Age"]=scaled_age

In [135]:
df.head()

,User ID,Age,EstimatedSalary,Purchased,Gender_Female,Gender_Male
0,15624510,-1.781797,-1.490046,0,0.0,1.0
1,15810944,-0.253587,-1.460681,0,0.0,1.0
2,15668575,-1.113206,-0.785290,0,1.0,0.0
3,15603246,-1.017692,-0.374182,0,1.0,0.0
4,15804002,-1.781797,0.183751,0,0.0,1.0


In [136]:
def Sigmoid(x):
    return 1/(1+np.exp(-x))
class LogisticRegression:
    def __init__(self,lr,epochs):
        self.coef_=None
        self.lr=lr
        self.epochs=epochs
    def fit(self,x,y):
        self.coef_=np.ones(x.shape[1])
        x=np.insert(x,0,1,axis=1)
        self.coef_=np.insert(self.coef_,0,0)
        for i in range(self.epochs):
            idx=np.random.randint(0,x.shape[0])
            y_pred=Sigmoid(np.dot(x[idx],self.coef_))
            print(y_pred,y[idx])
            self.coef_=self.coef_+self.lr*(y[idx]-y_pred)*x[idx]
    def predict(self,x):
        x=np.insert(x,0,1,axis=1)
        return (np.dot(x,self.coef_)>0).astype(int)
        

In [137]:
model=LogisticRegression(0.001,10000)
x=df[['Age','EstimatedSalary','Gender_Male',"Gender_Female"]]
y=df['Purchased']

In [138]:
model.fit(x,y )

0.538040995546661 0
0.9403842777180881 1
0.7214010627161624 1
0.9492255604538583 1
0.5414682033902264 0
0.9532936973187537 1
0.6925297131954418 0
0.6923007315966908 0
0.46549601218590836 0
0.6934110283474212 1
0.6190704347410275 0
0.5730874311591976 1
0.7824031695649667 1
0.6364637570094822 0
0.7251328869698609 0
0.6013505579295436 0
0.5761889152541727 0
0.26099382158756773 0
0.6988432775308036 0
0.7973602926989748 0
0.5603802485210378 0
0.11585463546512541 0
0.987628231646044 1
0.962438541001355 1
0.8337838161196748 1
0.6262965477426465 0
0.9940647136386734 1
0.5777511955916338 0
0.5008246160677381 0
0.34493105466438573 0
0.5955214216856818 0
0.8749245677123824 1
0.7976603175477746 0
0.7486202735058608 0
0.34392228817545706 0
0.7805273563329271 1
0.8672447718365124 1
0.41473606731799517 0
0.975021384573133 0
0.3303308542813945 0
0.6184504475512748 0
0.39608642378587233 0
0.5095402240343202 0
0.8324311766719384 0
0.7216577932169149 0
0.21093849105743 0
0.9694418112938417 1
0.8800742590

In [139]:
model.coef_

array([-1.13709831,  1.57231309,  0.97368992,  0.43819202,  0.42470967])

In [140]:
y_pred=pd.DataFrame(model.predict(x))
y_pred.value_counts()

0
0    276
1    124
Name: count, dtype: int64

In [141]:
y.value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [142]:
class GDLogisticRegression:
    def __init__(self,lr,epochs):
        self.coef_=None
        self.lr=lr
        self.epochs=epochs
    def fit(self,x,y):
        self.coef_=np.ones(x.shape[1])
        x=np.insert(x,0,1,axis=1)
        self.coef_=np.insert(self.coef_,0,0)
        for i in range(self.epochs):
            y_pred=Sigmoid(np.dot(x,self.coef_))
            self.coef_=self.coef_+self.lr*np.dot((y-y_pred),x)/x.shape[0]
    def predict(self,x):
        x=np.insert(x,0,1,axis=1)
        return Sigmoid(np.dot(x,self.coef_))

In [148]:
model=GDLogisticRegression(1000,1000)
model.fit(x,y)


/tmp/ipykernel_9814/3768391463.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


In [149]:
model.predict(x)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 1.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.        , 0.        ,
       0.        , 0.55122552, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 1.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 1.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 1.        , 0.     

In [150]:
y.to_numpy()

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,