In [38]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [39]:
from sklearn.datasets import load_diabetes

In [40]:
x,y = load_diabetes(return_X_y=True)

In [41]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [42]:
x_train,x_test,y_train,y_test=train_test_split(
    x,
    y,
    random_state=42,
    test_size=0.2
    
)
model=LinearRegression()


In [43]:
model.fit(x_train,y_train)
x_test[0:2].reshape(-1,10)

array([[ 0.04534098, -0.04464164, -0.00620595, -0.01599898,  0.1250187 ,
         0.1251981 ,  0.019187  ,  0.03430886,  0.03243232, -0.0052198 ],
       [ 0.09256398, -0.04464164,  0.03690653,  0.02187239, -0.02496016,
        -0.01665815,  0.00077881, -0.03949338, -0.02251653, -0.02178823]])

In [44]:
y_pred=model.predict(x_test)
y_pred

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59

In [45]:
y_test
from sklearn.metrics import root_mean_squared_error
rmse=root_mean_squared_error(y_test,y_pred)

In [46]:
rmse


53.85344583676593

In [47]:
class MeraLr():
    def __init__(self):
        self.weights=None
    def fit(self,x_train,y_train):
        x_train = np.insert(x_train,0,1,axis=1)
        self.weights = np.linalg.inv(x_train.T.dot(x_train)).dot(x_train.T).dot(y_train)
    def predict(self, x_test):
        return x_test @ self.weights[1:] + self.weights[0]

In [48]:
model=MeraLr()
model.fit(x_train,y_train)
model.predict(x_test)

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59